version: '3'
services:
  postgres-db:
    image: postgres:11.5
    container_name: postgres
    cap_add:
      - IPC_LOCK
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sample

volumes:
  postgres-data:
    driver: local
